### ISSUE TITLE
OpenAPI SHOULD define an `ErrorCode` schema with a list of enum values

### ISSUE THREAD

**Issue by craicoverflow** [redhat-developer/app-services-api-guidelines#19]
Example:

```yaml
 ErrorCode:
      type: string
      enum:
        - "KAFKAS-MGMT-4"
        - "KAFKAS-MGMT-5"
        - "KAFKAS-MGMT-6"
```

This should then be referenced in the `Error` schema `code` property.
